### ISSUE TITLE
Request: Ability to have a String wrapped "in place" using `&mut String`

### ISSUE THREAD

**Issue by Lokathor** [mgeisler/textwrap#166]
If I already have a String with a large backbuffer, I'd like the ability to apply wrapping to it by calling something like

```rust
textwrap::wrap_in_place(&mut message, textwrap::termwidth());
```

**Comment by mgeisler** [comment]
Hi @Lokathor, thanks for the suggestion, I think such a function would be very useful for simple cases where you just want to wrap an existing string quickly: you would simply replace some `' '` characters with `'\n'` characters, all without reallocating any memory.

More complicated cases where you do automatic hyphenation would probably still need to return a new `String` since there you can end up adding extra `'-'` characters to the string. I've been working towards changing the underlying algorithm to make it easier to do wrapping which removes whitespace between words and add things like `'-'` characters.

However, I think having both a simple and fast reference algorithm and a more advanced algorithm would make sense. So I'll definitely keep it in mind!
