### ISSUE TITLE
The indent function always adds a final \n, even if the input string has no \n

### ISSUE THREAD

**Issue by jRimbault** [mgeisler/textwrap#207]
Example:

```rust
// this test fails currently
#[test]
fn indented_text_should_have_the_same_number_of_lines_as_the_original_text() {
    let texts = ["foo\nbar", "foo\nbar\n", "foo\nbar\nbaz"];
    for original in texts.iter() {
        let indented = indent(original, "");
        assert_eq!(&indented, original);
    }
}
```

There should be the same number of lines in the input and output (unless the prefix contains a newline).

[Python tests reference](https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Lib/test/test_textwrap.py), [python source reference](https://github.com/python/cpython/blob/a33f2c2bae759fc9d06e1c032fd2026135f2df45/Lib/textwrap.py#L465), can't be implemented the same way in rust without the [`split_inclusive`](https://github.com/rust-lang/rust/issues/72360) feature. (cf. python's [`splitlines`](https://docs.python.org/3/library/stdtypes.html#str.splitlines))

<details>
<summary>Python script passes the same test</summary>

```python
from textwrap import indent

for original in ["foo\nbar", "foo\nbar\n", "foo\nbar\nbaz"]:
    indented = indent(original, "")
    assert original == indented
```
</details>

**Comment by mgeisler** [comment]
Hi @jRimbault Thank you very much for the excellent bug report and the accompanying fixes!

Since it uses a nightly API, I guess we'll just let is sit and wait for a bit...?

In the mean time, I'll have to look at why the tests didn't actually break as expected! I recently switched to GitHub actions, but I must have misconfigured it somehow :-)

If I read #208 and #209 correctly, then I think #208 is a subset of #209? If so, I would prefer to close #208 and simply merge the tests together with the implementation.

**Comment by jRimbault** [comment]
I made #208 in case you wanted to merge the tests in some working branch of yours ?

I think waiting for the inclusive to be in stable shouldn't take too long, it's a simple feature and it's only missing a stabilization PR.

**Comment by mgeisler** [comment]
Thanks for the tip about fixing the GitHub workflow!

I don't have a working branch as such, so I'll just close #208 for now.
