### ISSUE TITLE
Separate soft line break finding and wrapping

### ISSUE THREAD

**Issue by Kestrer** [mgeisler/textwrap#230]
Currently this library does the soft line break finding and wrapping in one step to go from `&str` to `String`. However this is very inefficient for static blocks of text, which will require recalculating the soft line break positions every single time the viewport is resized. My suggestion is to have the wrapping functions take in an `impl Iterator<Item = &str>` and use that instead. Then instead of having the complex `WordSplitter` trait, we can have simple functions that take an `&str` and return an `Iterator<Item = &str>`.

If you're happy with the idea then I will work on this, I just need to get some feedback first.

**Comment by mgeisler** [comment]
Hi @Koxiaet,
I'm all for making things simpler and nicer :-) However, I'm afraid I don't understand what "soft line break" means here?

Are you talking about the "preliminary" splitting done in [`wrap`](https://github.com/mgeisler/textwrap/blob/master/src/lib.rs#L571)? Around the lines where I split the input text on all possible breakpoints and break apart long words:
```rust
        let words = core::find_words(line);
        let split_words = core::split_words(words, &options);
```

This should all be taking place on `&str` values, no `String` in sight. Perhaps you're thinking of something else?

**Comment by Koxiaet** [comment]
"Soft line break" refers to line break opportunities - the boundaries between words, punctuation etc, as opposed to hard line breaks (\n or \r\n).

> This should all be taking place on &str values, no String in sight.

I'm not quite sure what you mean by this, my proposal operates entirely on `&str`s.

**Comment by mgeisler** [comment]
I don't think I understand what your proposal is about :smile: 

You talk about a viewport which can be resized. Which viewport are you talking about here?

**Comment by Koxiaet** [comment]
By viewport I mean the terminal width. Say for example in a `less`-like program one might want to compute all the line break opportinities beforehand and run the textwrap function on the list of segments whenever the terminal resizes.

**Comment by mgeisler** [comment]
Ahh... thanks, I think I finally get it! You're talking about how we could make it possible for programs to cache and reuse the work to find the line break opportunities. I completely agree that this would be a nice feature!

Right now, `textwrap::wrap` is delegating some of its work to the function `textwrap::core` — I would be very happy to see all of the functionality moved out into separate functions so that `wrap` shrinks to something very simple. I like how the first part of the inner loop is just a series of function calls:

```rust
let words = core::find_words(line);
let split_words = core::split_words(words, &options);
let broken_words = if options.break_words {
    core::break_words(split_words, subsequent_width)
} else {
    split_words.collect::<Vec<_>>()
};
```

The rest of the loop could use some of the same thinking so that all of the building blocks become accessible to users of the library.

Simplifying the above a bit, a program could compute

```rust
let words = textwrap::core::split_words(textwrap::core::find_words(line), &options).collect::<Vec<_>>();
```

once and reuse this many times by basically running the remainder of the loop.

**Comment by Koxiaet** [comment]
I don't think we should separate `split_words` and `find_words`; ICU doesn't separate them in its API, and the functionalities of `NoHyphenation`/`HypenSplitter` can be implemented more simply using multiple functions.

**Comment by mgeisler** [comment]
Okay, `split_words` and `find_words` could certainly be combined into one function. There is actually some redundant calls to `width()` right now when the words are constructed in `find_words`: `split_words` sets the width again and doesn't care about the old width.

**Comment by Koxiaet** [comment]
I'm also wondering whether to change the naming of the functions. `Word`/`words` is somewhat of a misnomer because it's not about words, it's about line break opportunities. Some languages break by syllables or characters, and even in English I wouldn't really consider `Hello!` to be a word. That being said I'm not sure what a good name is here - maybe "chunk"?

**Comment by mgeisler** [comment]
> I'm also wondering whether to change the naming of the functions. `Word`/`words` is somewhat of a misnomer because it's not about words, it's about line break opportunities.

I was also on the fence on this myself in the beginning :-) At some point, I used the word `Segment` myself. I was also playing with `Span` instead of `Word` since this seems to convey "a span of characters" inside the bigger string that we're wrapping. However, since the spans were created by splitting a string on `' '`, it seemed that `Word` is the most descriptive name for this.

I think the name has to contrast a bit with the trait name. There I used `Fragment` as the name for "stuff we can wrap into lines". It would be a `Word`, it could be a `&str`, it could be some kind of `PdfString`, it could be a `TableCell` or something else entirely.

We could perhaps use `Span` as the name of the trait and `CharSpan` as the concrete type? I would be happy to have suggestions — we all know that naming is one of the hard problems in computer science :-)

**Comment by mgeisler** [comment]
When talking about names for this, let me just add that I also looked at names like `Box` instead of `Fragment`. That comes from TeX via the article [_Breaking Paragraphs into Lines_](http://www.eprg.org/G53DOC/pdfs/knuth-plass-breaking.pdf). I wrote a bit about it in #221, including how `box` is a reserved keyword and how `Box` is a struct in the Rust prelude which makes it a bit odd to use the same word here :shrug:

**Comment by Koxiaet** [comment]
I do like `Fragment`, I'm currently using `SpaceFragment` as it conveys the purpose better than `Word` I think. Using a `-Fragment` suffix also means we don't have to come up with more creative names for other types of fragment.

**Comment by mgeisler** [comment]
My thinking nowadays is that programs with state should

1. Split its text as needed into words/syllables/... units which it want to wrap. Textwrap has a few functions for this which operate on `&str`, but I expect programs to implement this with their own types (styled strings of some sort). The result is a list of `Fragment`s.
b) Wrap the fragments using `wrap_first_fit` or `wrap_optimal_fit`.
c) Render these fragments in some custom way.

That is, the top-level functions such as `wrap` is the interface if you want to wrap a `&str` and do it once. If you want to do it repeatedly, then it should be possible to reach into the guts of `wrap` and replicate the parts needed.

I'll close this issue now. If you still have ideas for how to make things simpler and more flexible, then let's talk about them in new specific issues.
