### ISSUE TITLE
Make `fill_inplace` take an &mut str

### ISSUE THREAD

**Issue by Kestrer** [mgeisler/textwrap#278]
Since it doesn't change the length of the string, it can take an `&mut str` instead of an `&mut String`. This will remove one layer of indirection and make it more flexible.

**Comment by mgeisler** [comment]
I just looked at this and I now remember why `fill_inplace` takes a `&mut String` instead of `&mut str`: I cannot find a suitable [`into_bytes`](https://doc.rust-lang.org/std/string/struct.String.html#method.into_bytes) method for [`&str`](file:///home/mg/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/doc/rust/html/std/primitive.str.html).

There is a [`as_bytes_mut`](https://doc.rust-lang.org/std/primitive.str.html#method.as_bytes_mut) method, but it is `unsafe`. Have I missed some other option to convert a `&str` into `[u8]` in-place?

**Comment by Kestrer** [comment]
I don't think there's a way to do this using just the standard library without `unsafe`. I created the [`with-str-bytes`](https://docs.rs/with-str-bytes) crate to allow this to be performed safely, if you don't mind another dependency (it's tiny - the entire crate including tests is just 132 lines).

**Comment by mgeisler** [comment]
Hey @Kestrer, okay, good to hear that I probably didn't miss anything here. Sorry for the late responses, recently I've found little time for open source work.

I'll pass on adding a new dependency for this — while it would be pretty if the signature was `&mut str`, I don't think it's a huge problem that the function demands a `String`.
