### ISSUE TITLE
Opening whitespaces causes empty first line

### ISSUE THREAD

**Issue by truchi** [mgeisler/textwrap#307]
```rust
let lines = wrap("  Hello, world!", 6)
    .iter()
    .map(|line| format!("|{}|\n", line))
    .collect::<String>();

println!("{}", lines);
```

Outputs:
```
||
|Hello,|
|world!|
```

Expecting (maybe?):
```
|Hello,|
|world!|
```

**Comment by mgeisler** [comment]
Hi @truchi,

This is an interesting corner case! Thanks for reminding me to document it. I've now put up #308 which adds some documentation and explanations about this.

I agree that it's a little ambiguous what to expect in this case: if we go with
```
|Hello,|
|world!|
```
Then we've effectively lost the whitespace. I kind of like that `"  Hello, world!"` wraps differently than `"Hello, world!"` here.

Please take a look at #308 and let me know if the details there make sense to you!

**Comment by truchi** [comment]
Yes, very clear!

**Comment by mgeisler** [comment]
Thanks, then I'll say that this issue is closed — while the empty first line might look odd at first, it's at least consistent with the scheme of attaching whitespace to the end of words. Further, wrapping with a width so narrow that the first word doesn't fit with the indentation is a bit of a corner-case: it's hard to decide what the right output should be in this case.
