### ISSUE TITLE
Some API-change suggestions

### ISSUE THREAD

**Issue by NeverGivinUp** [mgeisler/textwrap#351]
Hi Martin,

I'd like to suggest some API- changes
1. `Word`s don't know their own context. They stand alone. One way to markup text is to have a list of spans of properties (like text-color, -size, superscripted, etc.). To get the width of some text fragment as well as to draw it marked up, the fragment needs to know, where it comes from -- its "global" position in the original text-string. Can `Word`s, as returned from `WordSeparator`s and `split_words` carry that information?
2. Currently `split_words` takes an iterator of words and returns split words for all words. I'd need a way to exempt some split points the hyphenator suggests. Like a closure, that is asked if a split point the splitter suggests is allowed or not. To make that decision based on markup spans, the closure would need to know the "global" index of the split point.
3. The `whitespace` and `penalty` fields of `Word` seem to be mutually exclusive. Would it make sense to replace them by say `enum PostFix {Whitespace(&str), Penalty(&str), None}`?

**Comment by mgeisler** [comment]
> * `Word`s don't know their own context. They stand alone. One way to markup text is to have a list of spans of properties (like text-color, -size, superscripted, etc.). To get the width of some text fragment as well as to draw it marked up, the fragment needs to know, where it comes from -- its "global" position in the original text-string. Can `Word`s, as returned from `WordSeparator`s and `split_words` carry that information?

Yeah, perhaps... :-)

The general idea was that you would use your own code to generate some struct which implements `Fragment`. The `Word` struct is "just" the struct that I came up with for wrapping text.

In the Wasm demo, I was "lucky" in the sense that I could [reuse the `Word` struct for the `CanvasWord` struct](https://github.com/mgeisler/textwrap/blob/master/examples/wasm/src/lib.rs#L166-L168). If I would have needed more information from the input (if the input was HTML or Markdown), I would have had to parse and split the text piece by piece and turn it into `Fragment`s in a more manual fashion.

> * Currently `split_words` takes an iterator of words and returns split words for all words. I'd need a way to exempt some split points the hyphenator suggests. Like a closure, that is asked if a split point the splitter suggests is allowed or not. To make that decision based on markup spans, the closure would need to know the "global" index of the split point.

I'm unsure if we can make `split_words` generic enough to work in other contexts. Since `split_words` is specific to the `Word` struct, I would instead prefer if you and others build the necessary infrastructure "around" the more generic interface given by the `WordSplitter` given by `Options` (if you want to use `Options` at all, it's really not necessary in general).

That is, just copy-paste the code in `split_words` and adapt it to your purpose!

The `split_words` code is very mechanical and you only need it you intend to split words further. Perhaps you can simply split the words as you go when you read your input? I _could_ have combined the `split_words` functionality with the initial "find me all the words" functionality expressed by the newly introduced `WordSeparator` trait.

I've added the `WordSeparator` and `WordSplitter` traits so that people can customize the wrapping of text for a terminal. Such text is simple: minimal formatting in the form of escape sequences and that's it. The escape sequences are unconditionally skipped when computing the display width of the text — if you instead get your text from a parse tree of some sort, then you know that there are no escape sequences and you should probably just some simpler mechanism to compute the width.

> * The `whitespace` and `penalty` fields of `Word` seem to be mutually exclusive. Would it make sense to replace them by say `enum PostFix {Whitespace(&str), Penalty(&str), None}`?

Yeah, I think you're right that they're mutually exclusive. I don't know of a use-case where it would be nice to have both, so I think we can turn them into an enum and save some space in each `Word` (a quick test says we would save 8 bytes on a 64-bit system where a `&str`` is 16 bytes). I would suggest having only two variants in the enum — the empty string can serve the role of your `None` variant.

Writing this, I imagine that the code that prints `word.whitespace` today will need to change to have a conditional: for every word, it would need to do `if let PostFix::Whitespace(whitespace) = word.post_fix` which could be more expensive than just accessing `word.whitespace` directly... If you start playing with this, then please keep an eye on the benchmarks. You can benchmark wrapping a large string with
```sh
$ cargo criterion optimal_fit_ascii/4800
````
This uses `cargo-criterion`.

**Comment by NeverGivinUp** [comment]
> In the Wasm demo, I was "lucky" in the sense that I could reuse the ´Word` struct for the `CanvasWord` struct. If I would have needed more information from the input (if the input was HTML or Markdown), I would have had to parse and split the text piece by piece and turn it into Fragments in a more manual fashion.

I understand now. Maybe add a comment in the examples and/or in the `Word` struct and the `split_words` function.
> parse and split the text piece by piece and turn it into Fragments in a more manual fashion. [...] That is, just copy-paste the code in `split_words` and adapt it to your purpose!

I am a master of Copy and Paste! I shall prevail over `Word` and `split_words`! 

> `if let PostFix::Whitespace(whitespace) = word.post_fix` [...] could be more expensive than just accessing `word.whitespace` directly... If you start playing with this, then please keep an eye on the benchmarks.

Will do, but I'm not worried. Small linear expenses usually aren't a problem. Algorithmic complexity that kills performance.

I wasn't suggesting this to save space -- though, that's always good, specially of data, that is used really, really often like this one --  I was aiming for more semantic clarity and a chance to encapsulate some behavior, too. If it's encapsulated having or not having a `None` becomes an implementation detail.

**Comment by mgeisler** [comment]
> I understand now. Maybe add a comment in the examples and/or in the `Word` struct and the `split_words` function.

Yeah, that would be a good idea. Could I get you to come up with a good comment? Something which would have helped you 2-3 days ago :-)


> Will do, but I'm not worried. Small linear expenses usually aren't a problem. Algorithmic complexity that kills performance.

You're right! I'll continue to play with extending the demo and if you find time, then feel free to submit a change which implements the enum idea.
