### ISSUE TITLE
Consider using strip-ansi-escapes crate 

### ISSUE THREAD

**Issue by luser** [mgeisler/textwrap#413]
I saw that you have code to strip ansi escape sequences in this crate. You might consider using this single-purpose crate I wrote to use in sccache: https://crates.io/crates/strip-ansi-escapes

It uses the extremely thorough `vte` crate to do the actual parsing bits, so it's very reliable. FWIW, cargo also uses my crate for this purpose. (For when it has cached compiler output containing escapes and needs to send it somewhere without colors enabled.)

**Comment by mgeisler** [comment]
Hi Ted,

Thanks for the pointer, I had not considered that there would be a crate for this :-)

Looking briefly at strip-ansi-escapes and vte, I don't think I need the features they offer — the tiny [`skip_ansi_escape_sequence`](https://docs.rs/textwrap/0.14.2/src/textwrap/core.rs.html#49-61) function seems to work well.

If Textwrap was a binary, then sure, an extra dependency wouldn't matter much. But since it's a library, I try to keep the dependencies to a minimum. It's my impression that this is a widespread trend in the Rust community, and I don't want extra dependencies to be a reason for people not to use Textwrap.
